### ISSUE TITLE
Why travis ci use thrift 9.1.0 while Dockerfile using 9.3.0

### ISSUE THREAD

**Issue by Wilbeibi** [pinterest/rocksplicator#158]
https://github.com/pinterest/rocksplicator/blob/cd5cc34029763acf940201d2854e6bd72f18187b/.travis.yml#L63

BTW, why fbthrift and apache thrift coexist here. From the code, I only see the fbthrift functions.

Thanks.

**Comment by newpoo** [comment]
We have python code for cluster management and java code in the controller, which need apache thrift.
