### ISSUE TITLE
questions 

### ISSUE THREAD

**Issue by zttaotao2013** [pinterest/rocksplicator#48]
hello,i read  have some questions after read the rocksplicator:
1)if the master is down,new master maybe promoted,perhaps the data maybe loss a little.
2)in the time of master promotion,the cluster maybe can't provide write service .
3)for one cluster，how it found the unavailable replication and recover it?ping perhaps only found node error.

**Comment by shuzhang1989** [comment]
thanks for reaching out!
we are building a rocksplicator controller to capture such kind of problems in a centralized place. it has a healthcheck task whcih periodically ping all hosts and check config to see if all shards are healthy.
if a host is down, ping is enough to capture the case. healthcheck task will trigger a series of tasks to replace the node.
if a host is removed from config but masters are not promoted yet, config file will not contain master role for certain shards and write will fail. but we will only enter this state when we are proactively removing a host from the config and do promotion. so it's a desired state during the failover.

**Comment by newpoo** [comment]
1. It depends on which replication mode you choose. It supports async replication, semi-sync replication, and sync replication. If async mode is used, yes, you may lose the data acked by the dead Master, but not yet replicated to any slaves yet. If you choose sync replication, no acked write will be lost, unless two or more hosts are dead simultaneously.

2. true, it can't support write for the shard being promoted. This is usually a few or even sub-second.

**Comment by zttaotao2013** [comment]
thanks for your replies!
i have another question : if i chose sync replication,one node down when writing data, the data may exist one replication but not exist in another,and the ack to client is wrote error for the data, but when reading first replication we may can get the data, could rocksplicator exist this this problem and how avoid it ? thx

**Comment by zttaotao2013** [comment]
sorry to trouble you for those questions above, for the questions,i want to confirm that whether rocksplicator can guarantee the consistency of the  replications at all case, because of one project in my hand use rocksdb,and i want to make replications for data safety,at first i want to use raft,but i feel very difficulty for this,then i found rocksplicator ,could you give some advises for me? thanks!

**Comment by newpoo** [comment]
We usually run it with one Master and two Slaves. So you will need to have both Slaves down. Because Master will ack client if any Slave has committed the write. There won't be a case where Master and Slave have different data permanently. They will always eventually be consistent.

We haven't added support for column families yet. Because we haven't found a need for it internally. I think it could be supported in future.

**Comment by zttaotao2013** [comment]
thank you,maybe i still have a problem to trouble you,very sorry to you!
rocksplicator sync data using rokcsdb wal which will delete for a period , by ttl or log size;for some problem such as the host down a period of time an restart,in this time the wal in master is delete ,so perhaps the sequencenum of slave request is not in master when slave pull request to master,for example,slave want to pull data of sequencenum 100,but  min sequencenum in master is 200,in this case,the master rocksdb getupdatesince interface only return the data after  sequencenum 200,then the data between 100-200 sequencenum is loss, i found rocksplicator  can't handle this case in code,pehaps i can't standand that, so i want to comfirm that wheher rocksplicator exsit this problem?

**Comment by newpoo** [comment]
In production, we configure the system to keep WAL for 1 hour, and set up monitoring alerts if the replication delay is more than 30 mins. Normally, it only takes a Slave a few hundreds of MS to fetch the latest writes from its Master. So we haven't seen this happens before. If it does happen, we will need to abandon Slaves, and rebuild new ones by backup.

**Comment by xiaoma2015** [comment]
hi, i have a question for rocksplicator  replication recently.  consider such case: if master node is down with the latest seq no for 100, and the latest seq no for slaves is 98, and the slave become master with latest seq no for 98. after a meanwhile, the master is up and become slave, and the new master's seq no is  101. according to seq no , the old master to be slave will pull data from the new master. how can rocksplicator handle this case ?
thank you !
