### ISSUE TITLE
Why use fbthrift，not use apache thrift?

### ISSUE THREAD

**Issue by xunliu** [pinterest/rocksplicator#497]
Is it because you need to rely on any special function in fbthrift?
I plan to use rocksplication in my own project,
Can I use thrift instead of fbthrift?

**Comment by newpoo** [comment]
Because fbthrift's C++ server is more performant than thrift's. this post has more details about it: https://engineering.fb.com/2014/02/20/open-source/under-the-hood-building-and-open-sourcing-fbthrift/

**Comment by xunliu** [comment]
@newpoo Thank you for your reply. :-)
